config/routes.rb
Pingu::Application.routes.draw do
  resources :penguins

end

app/models/penguin.rb
class Penguin < ActiveRecord::Base
	beak_max = 4;
	belly_max = 5;
	eyes_max = 4;
	body_max = 1;
	personalities = /(grumpy)|(downright jolly)|(serious)|(bold)|(serious)|(sassy)/
	colours = /(FF6666)|(AD85FF)/

	validates :name, length: { minimum: 3 ,maximum: 20}
	#validates_uniqueness_of :name, scope: :user_id

	validates :gender, length: {minimum:1 , maximum:1}
	validates_format_of :gender, :with=>/(f)|(m)/

	validates_format_of :personality, :with=>personalities

	validates :color_mum, length: {minimum:6 , maximum:6}
	validates_format_of :color_mum, :with=>colours
	validates :color_dad, length: {minimum:6 , maximum:6}
	validates_format_of :color_dad, :with=>colours
	validates :color_own, length: {minimum:6 , maximum:6}
	validates_format_of :color_own, :with=>colours

	validates :belly_color_mum, length: {minimum:6 , maximum:6}
	validates_format_of :belly_color_mum, :with=>colours
	validates :belly_color_dad, length: {minimum:6 , maximum:6}
	validates_format_of :belly_color_dad, :with=>colours
	validates :belly_color_own, length: {minimum:6 , maximum:6}
	validates_format_of :belly_color_own, :with=>colours

	validates :beak_mum, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: beak_max,
                                    only_integer: true }
	validates :beak_dad, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: beak_max,
                                    only_integer: true }
	validates :beak_own, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: beak_max,
                                    only_integer: true }
	validates :belly_mum, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: belly_max,
                                    only_integer: true }
	validates :belly_dad, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: belly_max,
                                    only_integer: true }
	validates :belly_own, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: belly_max,
                                    only_integer: true }
	validates :eyes_mum, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: eyes_max,
                                    only_integer: true }
	validates :eyes_dad, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: eyes_max,
                                    only_integer: true }
	validates :eyes_own, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: eyes_max,
                                    only_integer: true }
	validates :body_mum, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: body_max,
                                    only_integer: true }
	validates :body_dad, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: body_max,
                                    only_integer: true }
	validates :body_own, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: body_max,
                                    only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/penguins_controller.rb
class PenguinsController < ApplicationController
  before_action :set_penguin, only: [:show, :edit, :update, :destroy]

  # GET /penguins
  # GET /penguins.json
  def index
    @penguins = Penguin.all
  end

  # GET /penguins/1
  # GET /penguins/1.json
  def show
  end

  # GET /penguins/new
  def new
    @penguin = Penguin.new
  end

  # GET /penguins/1/edit
  def edit
  end

  # POST /penguins
  # POST /penguins.json
  def create
    @penguin = Penguin.new(penguin_params)

    respond_to do |format|
      if @penguin.save
        format.html { redirect_to @penguin, notice: 'Penguin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @penguin }
      else
        format.html { render action: 'new' }
        format.json { render json: @penguin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /penguins/1
  # PATCH/PUT /penguins/1.json
  def update
    respond_to do |format|
      if @penguin.update(penguin_params)
        format.html { redirect_to @penguin, notice: 'Penguin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @penguin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /penguins/1
  # DELETE /penguins/1.json
  def destroy
    @penguin.destroy
    respond_to do |format|
      format.html { redirect_to penguins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_penguin
      @penguin = Penguin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def penguin_params
      params.require(:penguin).permit(:name, :gender, :personality, :colour_mum, :colour_dad, :colour_own, :belly_colour_mum, :belly_colour_dad, :belly_colour_own, :beak_mum, :beak_dad, :beak_own, :eyes_mum, :eyes_dad, :eyes_own, :belly_mum, :belly_dad, :belly_own, :body_mum, :body_dad, :body_own)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/penguins_helper.rb
module PenguinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingu</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/penguins/_form.html.erb
<%= form_for(@penguin) do |f| %>
  <% if @penguin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@penguin.errors.count, "error") %> prohibited this penguin from being saved:</h2>

      <ul>
      <% @penguin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :personality %><br>
    <%= f.text_field :personality %>
  </div>
  <div class="field">
    <%= f.label :colour_mum %><br>
    <%= f.text_field :colour_mum %>
  </div>
  <div class="field">
    <%= f.label :colour_dad %><br>
    <%= f.text_field :colour_dad %>
  </div>
  <div class="field">
    <%= f.label :colour_own %><br>
    <%= f.text_field :colour_own %>
  </div>
  <div class="field">
    <%= f.label :belly_colour_mum %><br>
    <%= f.text_field :belly_colour_mum %>
  </div>
  <div class="field">
    <%= f.label :belly_colour_dad %><br>
    <%= f.text_field :belly_colour_dad %>
  </div>
  <div class="field">
    <%= f.label :belly_colour_own %><br>
    <%= f.text_field :belly_colour_own %>
  </div>
  <div class="field">
    <%= f.label :beak_mum %><br>
    <%= f.number_field :beak_mum %>
  </div>
  <div class="field">
    <%= f.label :beak_dad %><br>
    <%= f.number_field :beak_dad %>
  </div>
  <div class="field">
    <%= f.label :beak_own %><br>
    <%= f.number_field :beak_own %>
  </div>
  <div class="field">
    <%= f.label :eyes_mum %><br>
    <%= f.number_field :eyes_mum %>
  </div>
  <div class="field">
    <%= f.label :eyes_dad %><br>
    <%= f.number_field :eyes_dad %>
  </div>
  <div class="field">
    <%= f.label :eyes_own %><br>
    <%= f.number_field :eyes_own %>
  </div>
  <div class="field">
    <%= f.label :belly_mum %><br>
    <%= f.number_field :belly_mum %>
  </div>
  <div class="field">
    <%= f.label :belly_dad %><br>
    <%= f.number_field :belly_dad %>
  </div>
  <div class="field">
    <%= f.label :belly_own %><br>
    <%= f.number_field :belly_own %>
  </div>
  <div class="field">
    <%= f.label :body_mum %><br>
    <%= f.number_field :body_mum %>
  </div>
  <div class="field">
    <%= f.label :body_dad %><br>
    <%= f.number_field :body_dad %>
  </div>
  <div class="field">
    <%= f.label :body_own %><br>
    <%= f.number_field :body_own %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/penguins/edit.html.erb
<h1>Editing penguin</h1>

<%= render 'form' %>

<%= link_to 'Show', @penguin %> |
<%= link_to 'Back', penguins_path %>

app/views/penguins/index.html.erb
<h1>Listing penguins!</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Personality</th>
      <th>Colour mum</th>
      <th>Colour dad</th>
      <th>Colour own</th>
      <th>Belly colour mum</th>
      <th>Belly colour dad</th>
      <th>Belly colour own</th>
      <th>Beak mum</th>
      <th>Beak dad</th>
      <th>Beak own</th>
      <th>Eyes mum</th>
      <th>Eyes dad</th>
      <th>Eyes own</th>
      <th>Belly mum</th>
      <th>Belly dad</th>
      <th>Belly own</th>
      <th>Body mum</th>
      <th>Body dad</th>
      <th>Body own</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @penguins.each do |penguin| %>
      <tr>
        <td><%= penguin.name %></td>
        <td><%= penguin.gender %></td>
        <td><%= penguin.personality %></td>
        <td><%= penguin.colour_mum %></td>
        <td><%= penguin.colour_dad %></td>
        <td><%= penguin.colour_own %></td>
        <td><%= penguin.belly_colour_mum %></td>
        <td><%= penguin.belly_colour_dad %></td>
        <td><%= penguin.belly_colour_own %></td>
        <td><%= penguin.beak_mum %></td>
        <td><%= penguin.beak_dad %></td>
        <td><%= penguin.beak_own %></td>
        <td><%= penguin.eyes_mum %></td>
        <td><%= penguin.eyes_dad %></td>
        <td><%= penguin.eyes_own %></td>
        <td><%= penguin.belly_mum %></td>
        <td><%= penguin.belly_dad %></td>
        <td><%= penguin.belly_own %></td>
        <td><%= penguin.body_mum %></td>
        <td><%= penguin.body_dad %></td>
        <td><%= penguin.body_own %></td>
        <td><%= link_to 'Show', penguin %></td>
        <td><%= link_to 'Edit', edit_penguin_path(penguin) %></td>
        <td><%= link_to 'Destroy', penguin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Penguin', new_penguin_path %>

app/views/penguins/new.html.erb
<h1>New penguin</h1>

<%= render 'form' %>

<%= link_to 'Back', penguins_path %>

app/views/penguins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @penguin.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @penguin.gender %>
</p>

<p>
  <strong>Personality:</strong>
  <%= @penguin.personality %>
</p>

<p>
  <strong>Colour mum:</strong>
  <%= @penguin.colour_mum %>
</p>

<p>
  <strong>Colour dad:</strong>
  <%= @penguin.colour_dad %>
</p>

<p>
  <strong>Colour own:</strong>
  <%= @penguin.colour_own %>
</p>

<p>
  <strong>Belly colour mum:</strong>
  <%= @penguin.belly_colour_mum %>
</p>

<p>
  <strong>Belly colour dad:</strong>
  <%= @penguin.belly_colour_dad %>
</p>

<p>
  <strong>Belly colour own:</strong>
  <%= @penguin.belly_colour_own %>
</p>

<p>
  <strong>Beak mum:</strong>
  <%= @penguin.beak_mum %>
</p>

<p>
  <strong>Beak dad:</strong>
  <%= @penguin.beak_dad %>
</p>

<p>
  <strong>Beak own:</strong>
  <%= @penguin.beak_own %>
</p>

<p>
  <strong>Eyes mum:</strong>
  <%= @penguin.eyes_mum %>
</p>

<p>
  <strong>Eyes dad:</strong>
  <%= @penguin.eyes_dad %>
</p>

<p>
  <strong>Eyes own:</strong>
  <%= @penguin.eyes_own %>
</p>

<p>
  <strong>Belly mum:</strong>
  <%= @penguin.belly_mum %>
</p>

<p>
  <strong>Belly dad:</strong>
  <%= @penguin.belly_dad %>
</p>

<p>
  <strong>Belly own:</strong>
  <%= @penguin.belly_own %>
</p>

<p>
  <strong>Body mum:</strong>
  <%= @penguin.body_mum %>
</p>

<p>
  <strong>Body dad:</strong>
  <%= @penguin.body_dad %>
</p>

<p>
  <strong>Body own:</strong>
  <%= @penguin.body_own %>
</p>

<%= link_to 'Edit', edit_penguin_path(@penguin) %> |
<%= link_to 'Back', penguins_path %>